#!/bin/bash
# profile_serial.sh – DD2356 Serial PageRank profiling
#
# 用法:
#   ./serial/profile_serial.sh                                   # quick: 5x 计时
#   ./serial/profile_serial.sh --full                            # quick + gprof + perf
#   ./serial/profile_serial.sh --full data/polblogs.csv directed
#
# 输出 (--full):
#   results/gprof_<graph>.txt          – gprof flat profile + call graph
#   results/perf_stat_<graph>.txt      – perf hardware counters (if available)
#   results/hotspot_notes.md           – auto-extracted top hotspots (overwrites stub)
#
# 环境变量:
#   PR_PROFILE_REPEAT=500              – gprof/perf 内核重复次数 (默认 500)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SERIAL_DIR="$PROJECT_ROOT/serial"
RESULTS_DIR="$PROJECT_ROOT/results"
mkdir -p "$RESULTS_DIR"

MODE="quick"
if [ "$1" = "--full" ]; then MODE="full"; shift; fi

GRAPH="${1:-$PROJECT_ROOT/data/polblogs.csv}"
DIRECTION="${2:-directed}"
REPEAT_TIMING="${3:-5}"
REPEAT_PROFILE="${PR_PROFILE_REPEAT:-500}"

# Make GRAPH absolute so we can cd to PROJECT_ROOT safely
case "$GRAPH" in
    /*) ;;
    *)  GRAPH="$PROJECT_ROOT/$GRAPH" ;;
esac

GRAPH_NAME=$(basename "$GRAPH" .csv)
BINARY="$SERIAL_DIR/pagerank_serial"
BIN_PG="$SERIAL_DIR/pagerank_serial_pg"

# Build if missing or stale
if [ ! -f "$BINARY" ] || [ "$SERIAL_DIR/pagerank_serial.c" -nt "$BINARY" ]; then
    echo "[build] gcc -O2 -o $BINARY"
    gcc -O2 -o "$BINARY" "$SERIAL_DIR/pagerank_serial.c" -lm
fi

echo "========================================"
echo " DD2356 Serial PageRank – Profiling"
echo "========================================"
echo "Host         : $(uname -n)  ($(uname -sr))"
echo "Graph        : $GRAPH ($DIRECTION)"
echo "Timing runs  : $REPEAT_TIMING"
[ "$MODE" = "full" ] && echo "Profile reps : $REPEAT_PROFILE  (PR_REPEAT for gprof/perf)"
echo ""

# ─── Quick timing (always runs) ─────────────────────────────────────
TIMES=()
for i in $(seq 1 $REPEAT_TIMING); do
    echo -n "Run $i/$REPEAT_TIMING ... "
    START=$(date +%s%N)
    "$BINARY" "$GRAPH" "$DIRECTION" > /tmp/pr_run_$i.txt 2>&1
    END=$(date +%s%N)
    ELAPSED=$(awk "BEGIN {printf \"%.6f\", ($END - $START)/1e9}")
    TIMES+=($ELAPSED)
    echo "${ELAPSED} s"
done

echo ""
echo "--- Timing Summary ---"
python3 - "${TIMES[@]}" <<'PYEOF'
import sys
t = [float(x) for x in sys.argv[1:]]
m = sum(t)/len(t)
print(f"  Min  : {min(t):.6f} s")
print(f"  Max  : {max(t):.6f} s")
print(f"  Avg  : {m:.6f} s")
print(f"  Std  : {(sum((x-m)**2 for x in t)/len(t))**0.5:.6f} s")
PYEOF

# ─── Full mode: gprof + perf + hotspot notes ────────────────────────
if [ "$MODE" != "full" ]; then
    echo ""
    echo "(Tip: rerun with --full to generate gprof + perf reports in results/)"
    exit 0
fi

echo ""
echo "--- gprof ---"
echo "[build] gcc -O2 -pg -o $BIN_PG"
gcc -O2 -pg -o "$BIN_PG" "$SERIAL_DIR/pagerank_serial.c" -lm

GPROF_OUT="$RESULTS_DIR/gprof_${GRAPH_NAME}.txt"
echo "[run]   PR_REPEAT=$REPEAT_PROFILE  $BIN_PG ..."
( cd "$PROJECT_ROOT" \
  && PR_REPEAT="$REPEAT_PROFILE" "$BIN_PG" "$GRAPH" "$DIRECTION" \
       > "$RESULTS_DIR/perf_polblogs_stdout.txt" )

GPROF_OK=0
if [ -f "$PROJECT_ROOT/gmon.out" ]; then
    gprof "$BIN_PG" "$PROJECT_ROOT/gmon.out" > "$GPROF_OUT"
    rm -f "$PROJECT_ROOT/gmon.out"
    GPROF_OK=1
    echo "[out]   $GPROF_OUT"
else
    printf '%s\n' \
        "gprof unavailable on $(uname -n) ($(uname -sr))." \
        "gmon.out was not produced — -pg is unsupported on this host (e.g. macOS clang)." \
        "Re-run on KTH or Dardel to populate." \
        > "$GPROF_OUT"
    echo "[warn] gmon.out not produced — wrote stub to $GPROF_OUT"
fi

echo ""
echo "--- perf stat ---"
PERF_OUT="$RESULTS_DIR/perf_stat_${GRAPH_NAME}.txt"
PERF_OK=0
if command -v perf >/dev/null 2>&1; then
    echo "[run]   perf stat -e cycles,instructions,cache-references,cache-misses,..."
    if ( cd "$PROJECT_ROOT" \
         && PR_REPEAT="$REPEAT_PROFILE" perf stat \
              -e cycles,instructions,cache-references,cache-misses,L1-dcache-load-misses,LLC-load-misses \
              "$BINARY" "$GRAPH" "$DIRECTION" \
              > /dev/null 2> "$PERF_OUT" ); then
        PERF_OK=1
        echo "[out]   $PERF_OUT"
    else
        echo "[warn] perf failed (check /proc/sys/kernel/perf_event_paranoid)"
    fi
else
    echo "[skip] perf not installed on this host"
    printf '%s\n' \
        "perf unavailable on $(uname -n) ($(uname -sr))." \
        "Re-run on KTH or Dardel to populate." \
        > "$PERF_OUT"
fi

# ─── Auto-generate hotspot_notes.md from gprof flat profile ─────────
echo ""
echo "--- hotspot_notes.md ---"
NOTES="$RESULTS_DIR/hotspot_notes.md"
{
    echo "# Hotspot notes – ${GRAPH_NAME} (serial baseline)"
    echo ""
    echo "Generated by \`serial/profile_serial.sh --full\` on $(date -u +'%Y-%m-%d %H:%M UTC')."
    echo "- Host: \`$(uname -n)\` ($(uname -sr))"
    echo "- Graph: \`$GRAPH\` ($DIRECTION)"
    echo "- PR_REPEAT: $REPEAT_PROFILE"
    echo ""
    echo "## gprof flat profile (top functions)"
    echo ""
    if [ "$GPROF_OK" = "1" ]; then
        echo '```'
        awk '
            /^Flat profile:/ { in_flat=1 }
            in_flat { print }
            in_flat && /^Call graph/ { exit }
        ' "$GPROF_OUT" | head -25
        echo '```'
    else
        echo "_gprof did not produce data on this host_ — see \`results/gprof_${GRAPH_NAME}.txt\`."
        echo "Re-run \`serial/profile_serial.sh --full\` on KTH or Dardel."
    fi
    echo ""
    echo "## perf stat highlights"
    echo ""
    if [ "$PERF_OK" = "1" ]; then
        echo '```'
        head -40 "$PERF_OUT"
        echo '```'
    else
        echo "_perf did not produce data on this host_ — see \`results/perf_stat_${GRAPH_NAME}.txt\`."
        echo "Re-run \`serial/profile_serial.sh --full\` on KTH or Dardel."
    fi
    echo ""
    echo "## Sources"
    echo ""
    echo "- gprof full:    \`results/gprof_${GRAPH_NAME}.txt\`"
    echo "- perf stat:     \`results/perf_stat_${GRAPH_NAME}.txt\`"
    echo "- timing stdout: \`results/perf_polblogs_stdout.txt\`"
} > "$NOTES"
echo "[out]   $NOTES"

echo ""
echo "Done. Commit:  results/gprof_${GRAPH_NAME}.txt, results/perf_stat_${GRAPH_NAME}.txt, results/hotspot_notes.md"
